#ifndef __CONFIG_H
#define __CONFIG_H

//CONFIG_FOR_COMMAND


#define CONFIG_COMMAND_HEADER_SIZE 	      4
#define CONFIG_MAX_COMMAND_SIZE 		  16//256
#define CONFIG_MSG_DATA_SIZE    	     (CONFIG_MAX_COMMAND_SIZE - CONFIG_COMMAND_HEADER_SIZE)
#define CONFIG_SEQ_COMMAND_BUFFER_SIZE   16
#define CONFIG_MAX_DEVICE_SIZE  		 (CONFIG_MAX_COMMAND_SIZE - CONFIG_COMMAND_HEADER_SIZE) >> 1


//#define MAX_DEVICE_SIZE 6
//#define HEADER_SIZE 4  //4: Header + Length + FC + CS = 4byte
//#define MAX_MSG_SIZE 16
//#define MSG_DATA_SIZE (MAX_MSG_SIZE - HEADER_SIZE)


#endif
